name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [macos-latest]
        # os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      shell: bash
      run: |
        pip3 install pyinstaller

    - name: Build
      shell: bash
      run: |
        pyinstaller -D test.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with: 
        name: test_${{ runner.os }}
        path: |
          dist/*
